name: Release

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  release:
    name: Release & Publish
    runs-on: ubuntu-latest
    permissions:
      # permission for creating a GitHub release
      contents: write
      # permission for publishing to npm with provenance
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # fetch full commit history for correct release notes generation
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm
          registry-url: https://registry.npmjs.org/

      - name: Install deps
        run: pnpm install

      - name: Set version tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create release archive
        run: zip -r "${GITHUB_REPOSITORY##*/}-${tag}.zip" src/ package.json LICENSE README.md

      - name: Generate release notes
        run: pnpm release:gh-notes

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_NOTES=$(cat RELEASE.md)
          gh release create "$tag" \
            --title="$tag" \
            --notes "$RELEASE_NOTES" \
            --draft \
            "${GITHUB_REPOSITORY##*/}-${tag}.zip"

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public --provenance --no-git-checks